version: "3.7"
services:
#    aplication:
    app:
        build:
            args:
                user: sammy
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        container_name: travellist-app
        restart: unless-stopped
        working_dir: /var/www/
        depends_on:
            - redis
            - mysql
        volumes:
            - ./:/var/www
            - ./docker-server/php.ini:/usr/local/etc/php/conf.d/uploads.ini
        networks:
            - travellist

#    webserver:
    nginx:
        image: nginx:alpine
        container_name: travellist-nginx
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - ./:/var/www
            - ./docker-server/nginx:/etc/nginx/conf.d/
        networks:
            - travellist

#    database:
    mysql:
        image: 'mysql/mysql-server:8.0'
        container_name: travellist-mysql
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'sail-mysql:/var/lib/mysql'
        networks:
            - travellist
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}" ]
            retries: 3
            timeout: 5s

#   redis:
    redis:
        image: redis:alpine
        container_name: travellist-redis
        restart: unless-stopped
        command: redis-server --appendonly yes --requirepass "${REDIS_PASSWORD}"
        healthcheck:
            test: [ "CMD", "redis-cli", "ping" ]
            retries: 3
            timeout: 5s
        volumes:
            - 'docker-redis:/data'
        ports:
            - "8002:6379"
        networks:
            - travellist

networks:
    travellist:
        driver: bridge

volumes:
    docker-redis:
        driver: local
    sail-mysql:
        driver: local
