#!/bin/bash
set -e

cd /var/www
# Start the application
#composer install --optimize-autoloader --no-dev

# php artisan migrate:fresh --seed
#php artisan cache:clear
#php artisan config:clear
#php artisan route:clear
# update application cache
php artisan optimize

#production
#php artisan config:cache
#php artisan route:cache
#php artisan view:cache

php-fpm && /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
